apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowers
  template:
    metadata:
      labels:
        app: flowers
    spec:
      containers:
      - image: okteto.dev/flowers:latest
        name: flowers
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "dde4a564-126f-4ffd-9a48-5a22113b1474"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "dde4a564-126f-4ffd-9a48-5a22113b1474"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
