apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcokefej
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcokefej
  template:
    metadata:
      labels:
        app: dcokefej
    spec:
      containers:
      - image: okteto.dev/dcokefej:latest
        name: dcokefej
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ec0acbd1-e299-451a-bce5-2bae32d009f5"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "ec0acbd1-e299-451a-bce5-2bae32d009f5"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
