apiVersion: apps/v1
kind: Deployment
metadata:
  name: bighill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bighill
  template:
    metadata:
      labels:
        app: bighill
    spec:
      containers:
      - image: okteto.dev/bighill:latest
        name: bighill
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "c1d1104c-e41b-4bbc-96ba-938ff8a1c07e"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "c1d1104c-e41b-4bbc-96ba-938ff8a1c07e"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
