apiVersion: apps/v1
kind: Deployment
metadata:
  name: danliya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danliya
  template:
    metadata:
      labels:
        app: danliya
    spec:
      containers:
      - image: okteto.dev/danliya:latest
        name: danliya
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "e346bd6c-c5b0-43c9-bf10-50acb754fd54"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "e346bd6c-c5b0-43c9-bf10-50acb754fd54"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
