apiVersion: apps/v1
kind: Deployment
metadata:
  name: miuzouya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miuzouya
  template:
    metadata:
      labels:
        app: miuzouya
    spec:
      containers:
      - image: okteto.dev/miuzouya:latest
        name: miuzouya
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "c0c76c14-80fe-430a-a260-063e58dec305"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "c0c76c14-80fe-430a-a260-063e58dec305"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
