apiVersion: apps/v1
kind: Deployment
metadata:
  name: yertool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yertool
  template:
    metadata:
      labels:
        app: yertool
    spec:
      containers:
      - image: okteto.dev/yertool:latest
        name: yertool
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "daa70658-4a2d-4291-a1de-80903e4a0d51"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "daa70658-4a2d-4291-a1de-80903e4a0d51"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
