apiVersion: apps/v1
kind: Deployment
metadata:
  name: cause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cause
  template:
    metadata:
      labels:
        app: cause
    spec:
      containers:
      - image: okteto.dev/cause:latest
        name: cause
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "2a40b242-4cf1-4832-9239-43854b6f830e"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "2a40b242-4cf1-4832-9239-43854b6f830e"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
