apiVersion: apps/v1
kind: Deployment
metadata:
  name: cokepa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cokepa
  template:
    metadata:
      labels:
        app: cokepa
    spec:
      containers:
      - image: okteto.dev/cokepa:latest
        name: cokepa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d5270297-9bee-4ddf-984f-4e4a39c45e25"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "d5270297-9bee-4ddf-984f-4e4a39c45e25"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
