apiVersion: apps/v1
kind: Deployment
metadata:
  name: xoution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xoution
  template:
    metadata:
      labels:
        app: xoution
    spec:
      containers:
      - image: okteto.dev/xoution:latest
        name: xoution
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "34a6aee7-da5e-4594-be85-19c7e3bd0754"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "34a6aee7-da5e-4594-be85-19c7e3bd0754"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
