apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunwa
  template:
    metadata:
      labels:
        app: bunwa
    spec:
      containers:
      - image: okteto.dev/bunwa:latest
        name: bunwa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b63d897b-3602-4b41-8b73-af93194b0e1c"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "b63d897b-3602-4b41-8b73-af93194b0e1c"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
