apiVersion: apps/v1
kind: Deployment
metadata:
  name: ougpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ougpanda
  template:
    metadata:
      labels:
        app: ougpanda
    spec:
      containers:
      - image: okteto.dev/ougpanda:latest
        name: ougpanda
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "06ffadb2-f47a-486f-af3e-1af86164ad33"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "06ffadb2-f47a-486f-af3e-1af86164ad33"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
