apiVersion: apps/v1
kind: Deployment
metadata:
  name: airfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airfer
  template:
    metadata:
      labels:
        app: airfer
    spec:
      containers:
      - image: okteto.dev/airfer:latest
        name: airfer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "3a7dd5a0-40cf-4510-b961-724e9738ac7b"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "3a7dd5a0-40cf-4510-b961-724e9738ac7b"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
