apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuipol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuipol
  template:
    metadata:
      labels:
        app: cuipol
    spec:
      containers:
      - image: okteto.dev/cuipol:latest
        name: cuipol
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f197da60-4041-48c1-9e21-b3a577529e33"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "f197da60-4041-48c1-9e21-b3a577529e33"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
