apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedoucu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedoucu
  template:
    metadata:
      labels:
        app: fedoucu
    spec:
      containers:
      - image: okteto.dev/fedoucu:latest
        name: fedoucu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "56a1ba24-de07-4827-b31e-8fc0a236d6a4"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "56a1ba24-de07-4827-b31e-8fc0a236d6a4"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
