apiVersion: apps/v1
kind: Deployment
metadata:
  name: cendoqa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cendoqa
  template:
    metadata:
      labels:
        app: cendoqa
    spec:
      containers:
      - image: okteto.dev/cendoqa:latest
        name: cendoqa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a7e212ba-05e2-4604-8832-9c3f546074d7"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "a7e212ba-05e2-4604-8832-9c3f546074d7"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
