apiVersion: apps/v1
kind: Deployment
metadata:
  name: coujikeo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coujikeo
  template:
    metadata:
      labels:
        app: coujikeo
    spec:
      containers:
      - image: okteto.dev/coujikeo:latest
        name: coujikeo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "43606357-0632-46ff-9ed3-a53cc0188f79"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "43606357-0632-46ff-9ed3-a53cc0188f79"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
