apiVersion: apps/v1
kind: Deployment
metadata:
  name: husouji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: husouji
  template:
    metadata:
      labels:
        app: husouji
    spec:
      containers:
      - image: okteto.dev/husouji:latest
        name: husouji
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "56a1ba24-de07-4827-b31e-8fc0a236d6a4"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "56a1ba24-de07-4827-b31e-8fc0a236d6a4"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
