apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliyea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliyea
  template:
    metadata:
      labels:
        app: aliyea
    spec:
      containers:
      - image: okteto.dev/aliyea:latest
        name: aliyea
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "80d9108f-c591-4422-a2d8-a455a45669fb"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "80d9108f-c591-4422-a2d8-a455a45669fb"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
