apiVersion: apps/v1
kind: Deployment
metadata:
  name: aofanm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aofanm
  template:
    metadata:
      labels:
        app: aofanm
    spec:
      containers:
      - image: okteto.dev/aofanm:latest
        name: aofanm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "83b39f08-999a-4d2c-9ef1-326bd15b5d3e"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "83b39f08-999a-4d2c-9ef1-326bd15b5d3e"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
