apiVersion: apps/v1
kind: Deployment
metadata:
  name: xoesyut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xoesyut
  template:
    metadata:
      labels:
        app: xoesyut
    spec:
      containers:
      - image: okteto.dev/xoesyut:latest
        name: xoesyut
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7e0ad09e-c615-456a-919b-cc6090a3cf14"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "7e0ad09e-c615-456a-919b-cc6090a3cf14"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
