apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerokell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerokell
  template:
    metadata:
      labels:
        app: zerokell
    spec:
      containers:
      - image: okteto.dev/zerokell:latest
        name: zerokell
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "53f64bcc-83dc-4a85-a7c6-e36fe24b9413"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "53f64bcc-83dc-4a85-a7c6-e36fe24b9413"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
