apiVersion: apps/v1
kind: Deployment
metadata:
  name: doudise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doudise
  template:
    metadata:
      labels:
        app: doudise
    spec:
      containers:
      - image: okteto.dev/doudise:latest
        name: doudise
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d9baa459-b27c-410a-8a22-d12ff941981b"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "d9baa459-b27c-410a-8a22-d12ff941981b"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
