apiVersion: apps/v1
kind: Deployment
metadata:
  name: flateng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flateng
  template:
    metadata:
      labels:
        app: flateng
    spec:
      containers:
      - image: okteto.dev/flateng:latest
        name: flateng
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "62289f13-ce0b-40c0-b5a8-7453338c4f3d"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "62289f13-ce0b-40c0-b5a8-7453338c4f3d"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
