apiVersion: apps/v1
kind: Deployment
metadata:
  name: xitaoh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xitaoh
  template:
    metadata:
      labels:
        app: xitaoh
    spec:
      containers:
      - image: okteto.dev/xitaoh:latest
        name: xitaoh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "eb32ffaa-3c22-45d5-a146-82874649acfa"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "eb32ffaa-3c22-45d5-a146-82874649acfa"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
