apiVersion: apps/v1
kind: Deployment
metadata:
  name: outward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outward
  template:
    metadata:
      labels:
        app: outward
    spec:
      containers:
      - image: okteto.dev/outward:latest
        name: outward
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "eafb226d-9c9b-4430-8d9e-4a3411a1dfcd"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "eafb226d-9c9b-4430-8d9e-4a3411a1dfcd"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
