apiVersion: apps/v1
kind: Deployment
metadata:
  name: observe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observe
  template:
    metadata:
      labels:
        app: observe
    spec:
      containers:
      - image: okteto.dev/observe:latest
        name: observe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "da4a91f4-c8e5-4039-b1b3-850d48d82a28"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "da4a91f4-c8e5-4039-b1b3-850d48d82a28"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
