apiVersion: apps/v1
kind: Deployment
metadata:
  name: bierteo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bierteo
  template:
    metadata:
      labels:
        app: bierteo
    spec:
      containers:
      - image: okteto.dev/bierteo:latest
        name: bierteo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6e81d1da-1d21-4126-a9d1-0a3c2eba1a7d"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "6e81d1da-1d21-4126-a9d1-0a3c2eba1a7d"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
