apiVersion: apps/v1
kind: Deployment
metadata:
  name: vooldet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vooldet
  template:
    metadata:
      labels:
        app: vooldet
    spec:
      containers:
      - image: okteto.dev/vooldet:latest
        name: vooldet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ef1c92d9-35b1-4582-9d17-f07c78ff3a71"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "ef1c92d9-35b1-4582-9d17-f07c78ff3a71"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
