apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuyading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuyading
  template:
    metadata:
      labels:
        app: cuyading
    spec:
      containers:
      - image: okteto.dev/cuyading:latest
        name: cuyading
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b135129a-3c66-4442-98b2-60be805f254f"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "b135129a-3c66-4442-98b2-60be805f254f"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
