apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuerose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuerose
  template:
    metadata:
      labels:
        app: yuerose
    spec:
      containers:
      - image: okteto.dev/yuerose:latest
        name: yuerose
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "d5b772a3-e31d-4ca5-adca-0251214e0773"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "d5b772a3-e31d-4ca5-adca-0251214e0773"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
