apiVersion: apps/v1
kind: Deployment
metadata:
  name: biugoig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biugoig
  template:
    metadata:
      labels:
        app: biugoig
    spec:
      containers:
      - image: okteto.dev/biugoig:latest
        name: biugoig
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f6e60cf3-6e5d-4ff3-8c33-e314fd03a35f"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "f6e60cf3-6e5d-4ff3-8c33-e314fd03a35f"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
