apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bingafe
  template:
    metadata:
      labels:
        app: bingafe
    spec:
      containers:
      - image: okteto.dev/bingafe:latest
        name: bingafe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "530c5667-d819-4901-b0b9-b4f146fbaf84"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "530c5667-d819-4901-b0b9-b4f146fbaf84"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
