apiVersion: apps/v1
kind: Deployment
metadata:
  name: maked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maked
  template:
    metadata:
      labels:
        app: maked
    spec:
      containers:
      - image: okteto.dev/maked:latest
        name: maked
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7fcf457e-6621-4018-9d08-f988adfc3753"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "7fcf457e-6621-4018-9d08-f988adfc3753"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
