apiVersion: apps/v1
kind: Deployment
metadata:
  name: govie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govie
  template:
    metadata:
      labels:
        app: govie
    spec:
      containers:
      - image: okteto.dev/govie:latest
        name: govie
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "pixabay.com"
        - name: Vless_UUID
          value: "d5b772a3-e31d-4ca5-adca-0251214e0773"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "d5b772a3-e31d-4ca5-adca-0251214e0773"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
