apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcockerou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcockerou
  template:
    metadata:
      labels:
        app: dcockerou
    spec:
      containers:
      - image: okteto.dev/dcockerou:latest
        name: dcockerou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a6a65ffd-77d4-4fd7-b63a-a826d5140f2e"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "a6a65ffd-77d4-4fd7-b63a-a826d5140f2e"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
