apiVersion: apps/v1
kind: Deployment
metadata:
  name: impulses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impulses
  template:
    metadata:
      labels:
        app: impulses
    spec:
      containers:
      - image: okteto.dev/impulses:latest
        name: impulses
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "54b45511-da09-4195-bae5-cc80b9f8d55d"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "54b45511-da09-4195-bae5-cc80b9f8d55d"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
