apiVersion: apps/v1
kind: Deployment
metadata:
  name: something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: something
  template:
    metadata:
      labels:
        app: something
    spec:
      containers:
      - image: okteto.dev/something:latest
        name: something
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "63d4f153-93c4-4cab-9419-e2ccdf28e6a0"
        - name: Vless_Path
          value: "/vlsou"
        - name: Vmess_UUID
          value: "63d4f153-93c4-4cab-9419-e2ccdf28e6a0"
        - name: Vmess_Path
          value: "/vmsou"
        - name: Share_Path
          value: "$Share_Path"
