apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbupuch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbupuch
  template:
    metadata:
      labels:
        app: dbupuch
    spec:
      containers:
      - image: okteto.dev/dbupuch:latest
        name: dbupuch
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7a4f64d2-7d5a-40c4-bc40-c68a8402401c"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "7a4f64d2-7d5a-40c4-bc40-c68a8402401c"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
