apiVersion: apps/v1
kind: Deployment
metadata:
  name: betasun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betasun
  template:
    metadata:
      labels:
        app: betasun
    spec:
      containers:
      - image: okteto.dev/betasun:latest
        name: betasun
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "74f2485c-16b3-4b87-b141-1d0e00178c62"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "74f2485c-16b3-4b87-b141-1d0e00178c62"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
