apiVersion: apps/v1
kind: Deployment
metadata:
  name: bearan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bearan
  template:
    metadata:
      labels:
        app: bearan
    spec:
      containers:
      - image: okteto.dev/bearan:latest
        name: bearan
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "58bf73f5-083d-4597-9a7c-50811912d1bf"
        - name: Vless_Path
          value: "/vldouli"
        - name: Vmess_UUID
          value: "58bf73f5-083d-4597-9a7c-50811912d1bf"
        - name: Vmess_Path
          value: "/vmhenfu"
        - name: Share_Path
          value: "$Share_Path"
