apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceavent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceavent
  template:
    metadata:
      labels:
        app: ceavent
    spec:
      containers:
      - image: okteto.dev/ceavent:latest
        name: ceavent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6d8f1cf1-06ad-43b5-a3ac-932f77d995ff"
        - name: Vless_Path
          value: "/vlmoon"
        - name: Vmess_UUID
          value: "6d8f1cf1-06ad-43b5-a3ac-932f77d995ff"
        - name: Vmess_Path
          value: "/vmfect"
        - name: Share_Path
          value: "$Share_Path"
