apiVersion: apps/v1
kind: Deployment
metadata:
  name: teniyakieto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teniyakieto
  template:
    metadata:
      labels:
        app: teniyakieto
    spec:
      containers:
      - image: okteto.dev/teniyakieto:latest
        name: teniyakieto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "654213c5-1142-41f3-b854-dfbef253b48a"
        - name: Vless_Path
          value: "/vlepoolyu"
        - name: Vmess_UUID
          value: "654213c5-1142-41f3-b854-dfbef253b48a"
        - name: Vmess_Path
          value: "/vmepoolyu"
        - name: Share_Path
          value: "$Share_Path"
