apiVersion: v1
kind: Service
metadata:
  name: flowers
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "flowers"
    port: 8080
  selector:
    app: flowers
