apiVersion: v1
kind: Service
metadata:
  name: cokepa
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "cokepa"
    port: 8080
  selector:
    app: cokepa
